# -*- mode: ruby -*-
# vi: set ft=ruby :

current_dir = File.dirname(File.expand_path(__FILE__))
Vagrant.configure("2") do |golmos|
  require './vagrant-provision-reboot-plugin'
  golmos.vm.box = "centos/7"
  golmos.vm.define "orasmus" do |orasmusvm|
    orasmusvm.vm.network :private_network, ip: "192.168.120.137"
    orasmusvm.vm.hostname = "orasmus"
    orasmusvm.ssh.forward_agent = true
    orasmusvm.vm.provider :virtualbox do |v1|
      v1.customize ["modifyvm", :id, "--memory", 1024]
      v1.customize ["modifyvm", :id, "--name", "orasmus"]
    end
    orasmusvm.vm.provision "shell", path: "scripts/install.sh"
    orasmusvm.vm.provision "shell", path: "scripts/nexusinstall.sh"
    orasmusvm.vm.provision :unix_reboot
  end
end
